src/SFA.DAS.Campaign.Web/Views/Home/Index.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/_Layout-campaign.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/_LayoutContent.cshtml
=> Fc 157 homepage

src/SFA.DAS.Campaign.Web/Controllers/IndustriesController.cs, src/SFA.DAS.Campaign.Web/Views/Employer/Index.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/AgricultureEnvironmentAnimalCare.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/BusinessAdministration.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/CareServices.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/CateringHospitality.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/Construction.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/CreativeDesign.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/Digital.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/EducationChildcare.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/EngineeringManufacturing.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/HairBeauty.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/HealthScience.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/Index.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/LegalFinanceAccounting.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/ProtectiveServices.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/SalesMarketingProcurement.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/TransportLogistics.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/_LayoutIndustry.cshtml
=> Fc 162 sector pages

src/SFA.DAS.Campaign.Web/Views/Employer/Index.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Components/_Footer.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Components/_Navigation.cshtml
- Footer update 
- Google Analytics IDs
=> Html changes

src/SFA.DAS.Campaign.Web/Views/Apprentice/FireUpYourApprenticeship.cshtml, src/SFA.DAS.Campaign.Web/Views/Apprentice/HowToGetYourApplicationRight.cshtml, src/SFA.DAS.Campaign.Web/Views/Apprentice/MonitorYourProgress.cshtml, src/SFA.DAS.Campaign.Web/Views/Apprentice/WhatAreTheStepsINeedToTake.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/ChooseATrainingProvider.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/HireAnApprentice.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/HowMuchIsItGoingToCost.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/PreparingAndMonitoring.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/TheRightApprenticeship.cshtml, src/SFA.DAS.Campaign.Web/Views/Home/Index.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/Index.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Components/Form/RegisterInterest.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Components/_Navigation.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Sidebar/_apprentice.cshtml
=> Fc xxx content iteration1

src/SFA.DAS.Campaign.Application.UnitTests/DataCollection/UserDataCollectionTests/WhenCollectingUserData.cs, src/SFA.DAS.Campaign.Application.UnitTests/DataCollection/UserDataCollectionTests/WhenValidatingUserData.cs, src/SFA.DAS.Campaign.Application/DataCollection/Services/UserDataCollection.cs, src/SFA.DAS.Campaign.Application/DataCollection/Validation/UserDataCollectionValidator.cs, src/SFA.DAS.Campaign.Domain/DataCollection/IUserDataCollectionValidator.cs, src/SFA.DAS.Campaign.Models/Validation/ValidationResult.cs, src/SFA.DAS.Campaign.Web.UnitTests/Controllers/EmailPreferences/WhenUserUpdatesEmailPreferences.cs, src/SFA.DAS.Campaign.Web.UnitTests/Controllers/RegisterInterest/WhenUserRegistersInterest.cs, src/SFA.DAS.Campaign.Web/Controllers/RegisterInterestController.cs, src/SFA.DAS.Campaign.Web/Models/RegisterInterestModel.cs, src/SFA.DAS.Campaign.Web/Views/Shared/Components/Form/RegisterInterest.cshtml
Include validation from service
=> FC-214 register validation

src/SFA.DAS.Campaign.Web/Startup.cs, src/SFA.DAS.Campaign.Web/Views/Home/Error.cshtml
@jamesmking Would it be possible for you to have a glance over the styling of this please? Also need to check with John Drinkwater that the responses in regards to GA tracking are correct before being merged. Easiest way to check is to hit a 404 to see what it currently looks like
=> FC-167 page not found and error

src/SFA.DAS.Campaign.Web.UnitTests/Controllers/RegisterInterest/WhenUserRegistersInterest.cs, src/SFA.DAS.Campaign.Web/Controllers/RegisterInterestController.cs
Changed the way that the return url is generated from the register
interest form, so that it is not completely reliant on the Referrer
=> FC-214 - Change to return url value

src/SFA.DAS.Campaign.Web/Views/Home/Index.cshtml
- Added 'Fire it up' to the homepage
- Links to stories
=> Homepage changes

src/.vscode/launch.json, src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj, src/SFA.DAS.Campaign.Web/Startup.cs
I've added usersecrets config provider and removed redundant config build to make is easier to run on Mac.
=> Add User Secrets

src/SFA.DAS.Campaign.Web/Views/Employer/Benefits.cshtml, src/SFA.DAS.Campaign.Web/Views/Industries/Index.cshtml, src/SFA.DAS.Campaign.Web/Views/RealStories/Apprentice.cshtml, src/SFA.DAS.Campaign.Web/Views/RealStories/Employer.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Components/HeroHeading/Default.cshtml
- FC-309 Add HM Gov Logo
- FC-455 'Benefits to your organisation' text change
=> FC-309 and FC-455

src/SFA.DAS.Campaign.Infrastructure/Configuration/AzureTableStorageConfigurationProvider.cs, src/SFA.DAS.Campaign.Infrastructure/Configuration/JsonConfigurationParser.cs, src/SFA.DAS.Campaign.Infrastructure/Configuration/StringExtensions.cs, src/SFA.DAS.Campaign.Infrastructure/SFA.DAS.Campaign.Infrastructure.csproj, src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj, src/SFA.DAS.Campaign.Web/Startup.cs, src/SFA.DAS.Campaign.Web/Views/Shared/Fat/ApprenticeshipDetails.cshtml, src/SFA.DAS.Campaign.Web/appsettings.json
This is the first pull request against the private-beta branch which was created from the latest FAT branch.
This relies on:
- the FAT Nuget Package in https://github.com/SkillsFundingAgency/das-search/pull/177
- the config changes in https://github.com/SkillsFundingAgency/das-employer-config/pull/272
=> FC-564 Initiate save

src/SFA.DAS.Campaign.Infrastructure/Configuration/AzureTableStorageConfigurationProvider.cs, src/SFA.DAS.Campaign.Infrastructure/Configuration/JsonConfigurationParser.cs, src/SFA.DAS.Campaign.Infrastructure/Configuration/StringExtensions.cs, src/SFA.DAS.Campaign.Infrastructure/SFA.DAS.Campaign.Infrastructure.csproj, src/SFA.DAS.Campaign.Web/Startup.cs
Enable the use of nested objects in config
=> Update parsing of azure config

src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj, src/SFA.DAS.Campaign.Web/Views/Home/Cookies.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Components/ApprenticeshipHeading/Default.cshtml
- Add save to favourites button to apprenticeship search results & details pages.
- Adds description for basket cookie to the cookie page.
=> FC-428 Add save to basket for apprenticeships

src/SFA.DAS.Campaign.Web/Views/Home/Countries.cshtml, src/SFA.DAS.Campaign.Web/Views/Parents/TheirCareer.cshtml
Simple update that changes ViewBag.Title and HeroHeading type.
=> Added missing question mark and removed the apprentice heading.

src/SFA.DAS.Campaign.Web/Views/Home/Index.cshtml
To allow text spacing to be overridden
=> Move h1 and additional class

azure/template.json
-Removed app service environment parameters
-Added appServiceAllowedIPs parameter
=> Transfer app services off App Service Environment

azure/template.json
Correct deployment of app service to app service plan
=> Correct deployment of app service to app service plan

src/SFA.DAS.Campaign.Web/Views/Shared/Components/Basket/Header/Default.cshtml
checks the apprenticeshipCount > 0
=> FC 815 adds a check to hide the create account button

src/SFA.DAS.Campaign.Infrastructure/Repositories/StandardsRepository.cs, src/SFA.DAS.Campaign.Infrastructure/Services/IIfaStandardsCacheService.cs, src/SFA.DAS.Campaign.Infrastructure/Services/IfaStandardsCacheService.cs, src/SFA.DAS.Campaign.UnitTests/Infrastructure/Repositories/WhenGettingAStandardFromTheService.cs, src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj, src/SFA.DAS.Campaign.Web/Startup.cs
Updates package and includes cache in the campaign site
=> updates shared components package to 1.2.0

src/SFA.DAS.Campaign.Web/Views/Home/TheCalling.cshtml
- Added BG video
- Change featured video to latest episode
- Added new bios
=> Jamal campaign updates

src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj, src/SFA.DAS.Campaign.Web/Views/Shared/TrainingProvider/Details.cshtml
Update for campaign website to include "not accepting new starters banner
=> FC-722 includes package 1.2.1 and rearranges header

src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj, src/SFA.DAS.Campaign.Web/Startup.cs
updates package and removes keywords from route definition
=> FC-1130 Search box after adding or removing from favourites

src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj, src/SFA.DAS.Campaign.Web/Views/Shared/Components/TrainingProviderHeading/Details.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/TrainingProvider/Details.cshtml
updates package number and adds postcode to form
=> FC-1198 Locations disappear when adding to favourites

src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj
updates component package to 1.2.12
=> FC-1321 on provider details page

src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj, src/SFA.DAS.Campaign.Web/ViewComponents/Apprenticeship-Heading/ApprenticeshipHeadingViewComponent.cs, src/SFA.DAS.Campaign.Web/ViewComponents/Apprenticeship-Heading/ApprenticeshipHeadingViewModel.cs, src/SFA.DAS.Campaign.Web/Views/Shared/Components/ApprenticeshipHeading/Default.cshtml
updates shared components to 1.2.14
=> FC-647 non-js confirmation messages

src/SFA.DAS.Campaign.Web/Views/Home/Countries.cshtml
updates meta data on the countries selection info page
=> FC-852 updates countries page metadata

src/SFA.DAS.Campaign.Web/SFA.DAS.Campaign.Web.csproj
=> FC-962 error message on training provider postcode

src/SFA.DAS.Campaign.Web/Controllers/EmployerInform/EndPointAssessmentsController.cs, src/SFA.DAS.Campaign.Web/Controllers/EmployerInform/TrainingYourApprenticeController.cs, src/SFA.DAS.Campaign.Web/Views/EmployerInform/EndPointAssessments.cshtml, src/SFA.DAS.Campaign.Web/Views/EmployerInform/TrainingYourApprentice.cshtml
Here's the content for the training your apprentice page.
James, could you look at the numbered bullet point section please.
=> FC-1338 training your apprentice page

src/SFA.DAS.Campaign.Web/Views/Shared/Components/Form/Register-Thanks.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Components/Modal/Modal.cshtml
- change buttons back into links
=> Fix to close modals

src/SFA.DAS.Campaign.Web/Views/Home/Sitemap.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Components/_Footer.cshtml, src/SFA.DAS.Campaign.Web/wwwroot/sitemap.xml
Links checked and updated. Footer link reinstated. XML spider file manually updated.
=> De 6 update site map page

src/SFA.DAS.Campaign.Web/Views/Shared/Panels/_FindTheRightApprenticeship.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Panels/_GetSupportEmployer.cshtml
All FAT tiles on employer side updated for create an advert instead
=> FAI-76 - Update tile content for recruit an apprentice from FAT

src/SFA.DAS.Campaign.Web/Views/CMS/Article.cshtml
Added a banner to notify users of how the traineeships delivery model is changing from August 2023.
=> ASCB-56 T Levels banner change

src/SFA.DAS.Campaign.Web/Views/Employer/ApprenticeshipBenefitsAndFunding.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/ValidationSummary.cshtml
Added validation order to viewbag on UFaB to order the error messages correctly
=> QF-1005 - Correcting error message ordering on UFaB

src/SFA.DAS.Campaign.Application/FundingTool/Queries/Calculation/CalculationQueryHandler.cs, src/SFA.DAS.Campaign.Application/FundingTool/Queries/Calculation/CalculationQueryResult.cs, src/SFA.DAS.Campaign.UnitTests/Application/ApprenticeshipBenefitsAndFunding/WhenCalculatingFundingAvailable.cs, src/SFA.DAS.Campaign.UnitTests/Web/Controllers/Employer/WhenRequestingTheCalculateYourApprenticeshipFundingPage.cs, src/SFA.DAS.Campaign.Web/Controllers/EmployerController.cs, src/SFA.DAS.Campaign.Web/Models/FundingYourApprenticeshipTrainingViewModel.cs, src/SFA.DAS.Campaign.Web/Views/Employer/ApprenticeshipBenefitsAndFunding.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/_CalculationInputPanel.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/_CalculationOutput.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/_CalculationResultsLevy.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/_CalculationResultsNonLevyOver50Employees.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/_CalculationResultsNonLevyUnder50Employees.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/_UseCases.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/_WhatToDoNext.cshtml, src/SFA.DAS.Campaign.Web/Views/Employer/_WhatYouPayNonLevy.cshtml, src/SFA.DAS.Campaign.Web/wwwroot/css/app.css
Enhancements and content changes to the 'Understanding apprenticeship benefits and funding' page/tool.
=> QF-1220 UFAB/ROI/UABAF Enhancements

src/SFA.DAS.Campaign.Web/Views/Employer/ApprenticeshipBenefitsAndFunding.cshtml, src/SFA.DAS.Campaign.Web/Views/LandingPages/ApprenticesLandingPage.cshtml, src/SFA.DAS.Campaign.Web/Views/Shared/Redesign_Layout_ApprenticesHub.cshtml
- Add support card to Useful resources and support landing page 
- Add additional link to Understanding apprenticeship benefits and funding page
=> FJA-196 FJA-198 content changes

src/SFA.DAS.Campaign.Web/Views/Employer/_CalculationInputPanel.cshtml
Move id tags from the radio-button-encompassing div tag to the input tag of the first radio button in the div. Remove the old id of the input tag and change the label for tag to match the new id.
=> QF-1318 Resolve inconsistent validation links

src/SFA.DAS.Campaign.Web/MiddleWare/AddRedirectRulesExtension.cs, src/SFA.DAS.Campaign.Web/Views/LandingPages/ApprenticesLandingPage.cshtml
- also removed a redundant hardcoded card
=> QF-1777 Add redirect for apprentice support pages
